name: Auto Update README

on:
  schedule:
    - cron: '*/5 * * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Example: Update README (replace with your script/command)
      - name: Run update script
        run: |
          # Example: echo the current time into README
          echo "Last updated: $(date -u)" > README.md

      - name: Commit and push if changed
        run: |
          git config --global user.name "jaymacaspac"
          git config --global user.email "jaymacaspac08@gmail.com"
          git add README.md
          git commit -m "Update README"
          git push
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
